### ISSUE TITLE
build a UI

### ISSUE THREAD

**Issue by leseb** [ceph/cn#29]
Possible projects to use:

* https://github.com/labstack/echo
* https://github.com/astaxie/beego
* https://github.com/gin-gonic/gin

**Comment by leseb** [comment]
Afterthoughts the UI could be a manager module instead of something from scratch. Perhaps a subset of the manager dashboard?

**Comment by pcuzner** [comment]
If you count python as a base, what about sree 
- https://github.com/cannium/Sree

**Comment by leseb** [comment]
I certainly do. The Go references are from scratch. Looks like Sree does the job out of the box. I'll give it a shot.

**Comment by leseb** [comment]
I guess my preferred solution for this would be to have a ceph-mgr module for this. It'd work really well with the multi-cluster support.
