### ISSUE TITLE
Issue spinning up latest-jewel cluster

### ISSUE THREAD

**Issue by blemmenes** [ceph/cn#38]
Here is the log output from trying to spin up a new jewel cluster using cn and -i to specify the image. This is a separate (empty) working dir for this execution so there should be no other files present.

This works if I specify luminous for everything.

**ceph-nano version v1.4.0 (HEAD/1b3d996)**

bash-4.4# cn cluster start -i ceph/daemon:latest-jewel jewel -d /tmp/cn_jewel  
2018/05/01 09:14:14 Running cluster jewel...                                   
2018/05/01 09:15:15 The container ceph-nano-jewel never reached a clean state. Showing the container logs now:                                                 
N2018-05-01 13:13:30  /entrypoint.sh: VERBOSE: activating bash debugging mode. 
s2018-05-01 13:13:30  /entrypoint.sh: To run Ceph daemons in debugging mode, pass the CEPH_ARGS variable like this:                                            
P2018-05-01 13:13:30  /entrypoint.sh: -e CEPH_ARGS='--debug-ms 1 --debug-osd 10'                                                                               
c2018-05-01 13:13:30  /entrypoint.sh: This container environement variables are: CEPH_DEMO_UID=nano                                                            
&HOSTNAME=ceph-nano-jewel-faa32aebf00b 
RGW_CIVETWEB_PORT=8000                 
        LC_ALL=C                       
DEMO_DAEMONS=mon,mgr,osd,rgw           
BPATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin             
NETWORK_AUTO_DETECT=4                  
PWD=/                                  
CEPH_VERSION=jewel                     
SHLVL=1                                

HOME=/root                             
CEPH_POINT_RELEASE=                    
CEPH_DAEMON=demo                       
DEBUG=verbose                          
_=/usr/bin/env                         
4ownership of '/var/run/ceph/' retained as ceph:ceph                           
Aownership of '/var/lib/ceph/bootstrap-osd' retained as ceph:ceph              
Aownership of '/var/lib/ceph/bootstrap-rgw' retained as ceph:ceph              
Ichanged ownership of '/var/lib/ceph/radosgw' from root:root to ceph:ceph      
ochanged ownership of '/var/lib/ceph/radosgw/ceph-rgw.ceph-nano-jewel-faa32aebf00b' from root:root to ceph:ceph                                                
Aownership of '/var/lib/ceph/bootstrap-mds' retained as ceph:ceph              
7ownership of '/var/lib/ceph/osd' retained as ceph:ceph                        
7ownership of '/var/lib/ceph/mds' retained as ceph:ceph                        
gchanged ownership of '/var/lib/ceph/mds/ceph-ceph-nano-jewel-faa32aebf00b' from root:root to ceph:ceph                                                        
7ownership of '/var/lib/ceph/tmp' retained as ceph:ceph                        
Tchanged ownership of '/var/lib/ceph/tmp/tmp.NqzHbGWrrC' from root:root to ceph:ceph                                                                           
7ownership of '/var/lib/ceph/mon' retained as ceph:ceph                        
gchanged ownership of '/var/lib/ceph/mon/ceph-ceph-nano-jewel-faa32aebf00b' from root:root to ceph:ceph                                                        
X2018-05-01 13:13:30  /entrypoint.sh: I can see existing Ceph files, please remove them!                                                                       
t2018-05-01 13:13:30  /entrypoint.sh: To run the demo container, remove the content of /var/lib/ceph/ and /etc/ceph/                                           
g2018-05-01 13:13:30  /entrypoint.sh: Before doing this, make sure you are removing any sensitive data.                                                        

2018/05/01 09:15:15 Please open an issue at: https://github.com/ceph/cn with the logs above.

**Comment by leseb** [comment]
Thanks for reporting this issue. The fix is pending here: https://github.com/ceph/ceph-container/pull/1041

A new image will be available in less than an hour. Thanks.

**Comment by blemmenes** [comment]
@leseb Thanks for the quick fix!

Seems to be a different issue now:
```
bash-4.4# cn cluster start -i ceph/daemon:latest-jewel jewel -d /tmp/cn_jewel  
The container image is not present, pulling it.                                
This operation can take a few minutes.........................................................................................................................................                                                                                                                                                
2018/05/02 08:39:41 Running cluster jewel...                                   
2018/05/02 08:40:13 Timeout while trying to reach: http://192.168.2.179:8000   
2018/05/02 08:40:13 S3 gateway for cluster ceph-nano-jewel is not responding. Showing S3 logs:                                                                 
2018/05/02 08:40:13 Error response from daemon: Container 48a242dda2ae26fad4a2787d479433521aa40e0e98a8dc11c2a32ed4575c32d3 is not running        
```
Here are the docker logs from the container
[docker-logs_ceph-nano-jewel.txt](https://github.com/ceph/cn/files/1967265/docker-logs_ceph-nano-jewel.txt)

Just to confirm, am I using the right image source?

Thanks,
Berant

**Comment by leseb** [comment]
@blemmenes I'm looking into this. Looks like you pulled a new image. But `docker images` will tell you how old `latest-jewel` is.

**Comment by blemmenes** [comment]
Yeah, just to be sure I purged the image.

ceph/daemon            latest-jewel        520f43bf166d        About an hour ago   564MB

**Comment by leseb** [comment]
That's the right image, debugging in progress.

**Comment by leseb** [comment]
Alright, https://github.com/ceph/ceph-container/pull/1042 should fix the issue.

**Comment by blemmenes** [comment]
Thanks @leseb 

Here's the image I'm on:
REPOSITORY             TAG                 IMAGE ID            CREATED             SIZE                                                                        
ceph/daemon            latest-jewel        8e84487a699d        42 minutes ago      564MB

New issue now:
bash-4.4# cn cluster start -i ceph/daemon:latest-jewel jewel -d /tmp/cn_jewel  
The container image is not present, pulling it.                                
This operation can take a few minutes..............................................................................................................................                                                                                                                                                           
2018/05/02 10:08:07 Running cluster jewel...                                   
2018/05/02 10:09:09 The container ceph-nano-jewel never reached a clean state. Showing the container logs now:                                                 
N2018-05-02 14:07:19  /entrypoint.sh: VERBOSE: activating bash debugging mode. 
s2018-05-02 14:07:19  /entrypoint.sh: To run Ceph daemons in debugging mode, pass the CEPH_ARGS variable like this:                                            
P2018-05-02 14:07:19  /entrypoint.sh: -e CEPH_ARGS='--debug-ms 1 --debug-osd 10'                                                                               
c2018-05-02 14:07:19  /entrypoint.sh: This container environement variables are: CEPH_DEMO_UID=nano                                                            
&HOSTNAME=ceph-nano-jewel-faa32aebf00b                                         
RGW_CIVETWEB_PORT=8000                                                         
        LC_ALL=C                                                               
DEMO_DAEMONS=mon,mgr,osd,rgw                                                   
BPATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin             
NETWORK_AUTO_DETECT=4                                                          
PWD=/                                                                          
CEPH_VERSION=jewel                                                             
SHLVL=1                                                                        

HOME=/root                                                                     
CEPH_POINT_RELEASE=                                                            
CEPH_DAEMON=demo                                                               
DEBUG=verbose                                                                  
_=/usr/bin/env                                                                 
4ownership of '/var/run/ceph/' retained as ceph:ceph                           
Aownership of '/var/lib/ceph/bootstrap-osd' retained as ceph:ceph              
Aownership of '/var/lib/ceph/bootstrap-rgw' retained as ceph:ceph              
Ichanged ownership of '/var/lib/ceph/radosgw' from root:root to ceph:ceph      
ochanged ownership of '/var/lib/ceph/radosgw/ceph-rgw.ceph-nano-jewel-faa32aebf00b' from root:root to ceph:ceph                                                
Aownership of '/var/lib/ceph/bootstrap-mds' retained as ceph:ceph              
7ownership of '/var/lib/ceph/osd' retained as ceph:ceph                        
7ownership of '/var/lib/ceph/mds' retained as ceph:ceph                        
gchanged ownership of '/var/lib/ceph/mds/ceph-ceph-nano-jewel-faa32aebf00b' from root:root to ceph:ceph                                                        
7ownership of '/var/lib/ceph/tmp' retained as ceph:ceph                        
Tchanged ownership of '/var/lib/ceph/tmp/tmp.qVy0UoWHA1' from root:root to ceph:ceph                                                                           
7ownership of '/var/lib/ceph/mon' retained as ceph:ceph                        
gchanged ownership of '/var/lib/ceph/mon/ceph-ceph-nano-jewel-faa32aebf00b' from root:root to ceph:ceph                                                        
-creating /etc/ceph/ceph.client.admin.keyring                                  
$creating /etc/ceph/ceph.mon.keyring                                           
2creating /var/lib/ceph/bootstrap-osd/ceph.keyring                             
2creating /var/lib/ceph/bootstrap-mds/ceph.keyring                             
2creating /var/lib/ceph/bootstrap-rgw/ceph.keyring                             
Nchanged ownership of '/etc/ceph/ceph.mon.keyring' from root:root to ceph:ceph 
\changed ownership of '/var/lib/ceph/bootstrap-osd/ceph.keyring' from root:root to ceph:ceph                                                                   
\changed ownership of '/var/lib/ceph/bootstrap-mds/ceph.keyring' from root:root to ceph:ceph                                                                   
\changed ownership of '/var/lib/ceph/bootstrap-rgw/ceph.keyring' from root:root to ceph:ceph                                                                   
.monmaptool: monmap file /etc/ceph/monmap-ceph                                 
=monmaptool: set fsid to ce83b7e1-64af-47e3-a652-8766986f5533                  
Bmonmaptool: writing epoch 0 to /etc/ceph/monmap-ceph (1 monitors)             
Ichanged ownership of '/etc/ceph/monmap-ceph' from root:root to ceph:ceph      
_importing contents of /var/lib/ceph/bootstrap-osd/ceph.keyring into /etc/ceph/ceph.mon.keyring                                                                
_importing contents of /var/lib/ceph/bootstrap-mds/ceph.keyring into /etc/ceph/ceph.mon.keyring                                                                
_importing contents of /var/lib/ceph/bootstrap-rgw/ceph.keyring into /etc/ceph/ceph.mon.keyring                                                                
Zimporting contents of /etc/ceph/ceph.client.admin.keyring into /etc/ceph/ceph.mon.keyring                                                                     
Vceph-mon: renaming mon.noname-a 172.17.0.2:6789/0 to mon.ceph-nano-jewel-faa32aebf00b                                                                         
;ceph-mon: set fsid to ce83b7e1-64af-47e3-a652-8766986f5533                    
tceph-mon: created monfs at /var/lib/ceph/mon/ceph-ceph-nano-jewel-faa32aebf00b for mon.ceph-nano-jewel-faa32aebf00b                                           
Wchanged ownership of '/etc/ceph/ceph.client.admin.keyring' from root:root to ceph:ceph                                                                        
Gchanged ownership of '/etc/ceph/ceph.conf' from root:root to ceph:ceph        
@ownership of '/etc/ceph/ceph.mon.keyring' retained as ceph:ceph               
Dchanged ownership of '/etc/ceph/rbdmap' from root:root to ceph:ceph           

2018/05/02 10:09:09 Please open an issue at: https://github.com/ceph/cn with the logs above.

**Comment by leseb** [comment]
Yup sorry one more patch :)

**Comment by blemmenes** [comment]
NP, throw in as many as you want. ;)

**Comment by leseb** [comment]
I think the last build will be the good one :).

**Comment by blemmenes** [comment]
Not quite yet.  Exec'ing into the container (which is actually running now) it looks like it is hung trying to create the nano user.

root       382  0.0  0.9 987812 18940 ?        Sl   17:10   0:00 radosgw-admin --cluster ceph user create --uid=nano --display-name=Ceph demo user

When I try to interact with radosgw-admin it just hangs (radosgw-admin metadata list user), though ceph -s shows HEALTH-OK.

bash-4.4# cn cluster start -i ceph/daemon:latest-jewel jewel -d /tmp/cn_jewel                                                                                                                                                                                                                                                 
2018/05/02 13:11:30 Running cluster jewel...                                                                                                                                                                                                                                                                                  
A2018/05/02 13:12:31 The container ceph-nano-jewel never reached a clean state. Showing the container logs now:                                                                                                                                                                                                               
N2018-05-02 17:10:50  /entrypoint.sh: VERBOSE: activating bash debugging mode.                                                                                                                                                                                                                                                
s2018-05-02 17:10:50  /entrypoint.sh: To run Ceph daemons in debugging mode, pass the CEPH_ARGS variable like this:                                                                                                                                                                                                           
P2018-05-02 17:10:50  /entrypoint.sh: -e CEPH_ARGS='--debug-ms 1 --debug-osd 10'                                                                                                                                                                                                                                              
c2018-05-02 17:10:50  /entrypoint.sh: This container environement variables are: CEPH_DEMO_UID=nano                                                                                                                                                                                                                           
&HOSTNAME=ceph-nano-jewel-faa32aebf00b                                                                                                                                                                                                                                                                                        
RGW_CIVETWEB_PORT=8000                                                                                                                                                                                                                                                                                                        
        LC_ALL=C                                                                                                                                                                                                                                                                                                              
DEMO_DAEMONS=mon,mgr,osd,rgw                                                                                                                                                                                                                                                                                                  
BPATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin                                                                                                                                                                                                                                                            
NETWORK_AUTO_DETECT=4                                                                                                                                                                                                                                                                                                         
PWD=/                                                                                                                                                                                                                                                                                                                         
CEPH_VERSION=jewel                                                                                                                                                                                                                                                                                                            
SHLVL=1                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                              
HOME=/root                                                                                                                                                                                                                                                                                                                    
CEPH_POINT_RELEASE=                                                                                                                                                                                                                                                                                                           
CEPH_DAEMON=demo                                                                                                                                                                                                                                                                                                              
DEBUG=verbose                                                                                                                                                                                                                                                                                                                 
_=/usr/bin/env                                                                                                                                                                                                                                                                                                                
4ownership of '/var/run/ceph/' retained as ceph:ceph                                                                                                                                                                                                                                                                          
Aownership of '/var/lib/ceph/bootstrap-osd' retained as ceph:ceph                                                                                                                                                                                                                                                             
Aownership of '/var/lib/ceph/bootstrap-rgw' retained as ceph:ceph                                                                                                                                                                                                                                                             
Ichanged ownership of '/var/lib/ceph/radosgw' from root:root to ceph:ceph                                                                                                                                                                                                                                                     
ochanged ownership of '/var/lib/ceph/radosgw/ceph-rgw.ceph-nano-jewel-faa32aebf00b' from root:root to ceph:ceph                                                                                                                                                                                                               
Aownership of '/var/lib/ceph/bootstrap-mds' retained as ceph:ceph                                                                                                                                                                                                                                                             
7ownership of '/var/lib/ceph/osd' retained as ceph:ceph                                                                                                                                                                                                                                                                       
7ownership of '/var/lib/ceph/mds' retained as ceph:ceph                                                                                                                                                                                                                                                                       
gchanged ownership of '/var/lib/ceph/mds/ceph-ceph-nano-jewel-faa32aebf00b' from root:root to ceph:ceph                                                        
7ownership of '/var/lib/ceph/tmp' retained as ceph:ceph                        
Tchanged ownership of '/var/lib/ceph/tmp/tmp.fBUQcwMfeB' from root:root to ceph:ceph                                                                           
7ownership of '/var/lib/ceph/mon' retained as ceph:ceph        
gchanged ownership of '/var/lib/ceph/mon/ceph-ceph-nano-jewel-faa32aebf00b' from root:root to ceph:ceph                                                        
-creating /etc/ceph/ceph.client.admin.keyring                                  
$creating /etc/ceph/ceph.mon.keyring                                           
2creating /var/lib/ceph/bootstrap-osd/ceph.keyring                             
2creating /var/lib/ceph/bootstrap-mds/ceph.keyring                             
2creating /var/lib/ceph/bootstrap-rgw/ceph.keyring                             
Nchanged ownership of '/etc/ceph/ceph.mon.keyring' from root:root to ceph:ceph 
\changed ownership of '/var/lib/ceph/bootstrap-osd/ceph.keyring' from root:root to ceph:ceph                                                                   
\changed ownership of '/var/lib/ceph/bootstrap-mds/ceph.keyring' from root:root to ceph:ceph                                                                   
\changed ownership of '/var/lib/ceph/bootstrap-rgw/ceph.keyring' from root:root to ceph:ceph                                                                   
.monmaptool: monmap file /etc/ceph/monmap-ceph                                 
=monmaptool: set fsid to 5be2856e-bf64-4950-bad2-92e42b85a643                  
Bmonmaptool: writing epoch 0 to /etc/ceph/monmap-ceph (1 monitors)             
Ichanged ownership of '/etc/ceph/monmap-ceph' from root:root to ceph:ceph      
_importing contents of /var/lib/ceph/bootstrap-osd/ceph.keyring into /etc/ceph/ceph.mon.keyring                                                                
_importing contents of /var/lib/ceph/bootstrap-mds/ceph.keyring into /etc/ceph/ceph.mon.keyring                                                                
_importing contents of /var/lib/ceph/bootstrap-rgw/ceph.keyring into /etc/ceph/ceph.mon.keyring                                                                
Zimporting contents of /etc/ceph/ceph.client.admin.keyring into /etc/ceph/ceph.mon.keyring                                                                     
Vceph-mon: renaming mon.noname-a 172.17.0.2:6789/0 to mon.ceph-nano-jewel-faa32aebf00b                                                                         
;ceph-mon: set fsid to 5be2856e-bf64-4950-bad2-92e42b85a643                    
tceph-mon: created monfs at /var/lib/ceph/mon/ceph-ceph-nano-jewel-faa32aebf00b for mon.ceph-nano-jewel-faa32aebf00b                                           
Wchanged ownership of '/etc/ceph/ceph.client.admin.keyring' from root:root to ceph:ceph                                                                        
Gchanged ownership of '/etc/ceph/ceph.conf' from root:root to ceph:ceph        
@ownership of '/etc/ceph/ceph.mon.keyring' retained as ceph:ceph               
Dchanged ownership of '/etc/ceph/rbdmap' from root:root to ceph:ceph           
Lchanged ownership of '/var/lib/ceph/osd/ceph-0' from root:root to ceph:ceph   
Cownership of '/var/lib/ceph/osd/ceph-0/fsid' retained as ceph:ceph            
Hownership of '/var/lib/ceph/osd/ceph-0/ceph_fsid' retained as ceph:ceph       
Downership of '/var/lib/ceph/osd/ceph-0/magic' retained as ceph:ceph           
>ownership of '/var/lib/ceph/osd/ceph-0' retained as ceph:ceph                 
\changed ownership of '/var/lib/ceph/osd/ceph-0/activate.monmap' from root:root to ceph:ceph                                                                   
Cownership of '/var/lib/ceph/osd/ceph-0/fsid' retained as ceph:ceph            
Hownership of '/var/lib/ceph/osd/ceph-0/ceph_fsid' retained as ceph:ceph       
Iownership of '/var/lib/ceph/osd/ceph-0/superblock' retained as ceph:ceph      
Lownership of '/var/lib/ceph/osd/ceph-0/store_version' retained as ceph:ceph   
Pownership of '/var/lib/ceph/osd/ceph-0/current/omap/LOCK' retained as ceph:ceph                                                                               
[ownership of '/var/lib/ceph/osd/ceph-0/current/omap/MANIFEST-000004' retained as ceph:ceph                                                                    
Oownership of '/var/lib/ceph/osd/ceph-0/current/omap/LOG' retained as ceph:ceph                                                                                
Sownership of '/var/lib/ceph/osd/ceph-0/current/omap/CURRENT' retained as ceph:ceph                                                                            
Vownership of '/var/lib/ceph/osd/ceph-0/current/omap/000005.log' retained as ceph:ceph                                                                         
Kownership of '/var/lib/ceph/osd/ceph-0/current/omap' retained as ceph:ceph    
nownership of '/var/lib/ceph/osd/ceph-0/current/meta/osd\\usuperblock__0_23C2FCDE__none' retained as ceph:ceph                                                 
Kownership of '/var/lib/ceph/osd/ceph-0/current/meta' retained as ceph:ceph    
Townership of '/var/lib/ceph/osd/ceph-0/current/commit_op_seq' retained as ceph:ceph                                                                           
Mownership of '/var/lib/ceph/osd/ceph-0/current/nosnap' retained as ceph:ceph  
Fownership of '/var/lib/ceph/osd/ceph-0/current' retained as ceph:ceph         
Downership of '/var/lib/ceph/osd/ceph-0/magic' retained as ceph:ceph           
Eownership of '/var/lib/ceph/osd/ceph-0/active' retained as ceph:ceph          
Eownership of '/var/lib/ceph/osd/ceph-0/whoami' retained as ceph:ceph          
Fownership of '/var/lib/ceph/osd/ceph-0/keyring' retained as ceph:ceph         
Cownership of '/var/lib/ceph/osd/ceph-0/type' retained as ceph:ceph            
Downership of '/var/lib/ceph/osd/ceph-0/ready' retained as ceph:ceph           
Fownership of '/var/lib/ceph/osd/ceph-0/journal' retained as ceph:ceph         
>ownership of '/var/lib/ceph/osd/ceph-0' retained as ceph:ceph                 
Ystarting osd.0 at :/0 osd_data /var/lib/ceph/osd/ceph-0 /var/lib/ceph/osd/ceph-0/journal                                                                      
wchanged ownership of '/var/lib/ceph/radosgw/ceph-rgw.ceph-nano-jewel-faa32aebf00b/keyring' from root:root to ceph:ceph                                        
aownership of '/var/lib/ceph/radosgw/ceph-rgw.ceph-nano-jewel-faa32aebf00b' retained as ceph:ceph                                                              
?2018-05-02 17:10:53  /entrypoint.sh: Setting up a demo user...                

2018/05/02 13:12:31 Please open an issue at: https://github.com/ceph/cn with the logs above.

**Comment by leseb** [comment]
One **last** commit, I promise... https://github.com/ceph/ceph-container/pull/1047

**Comment by blemmenes** [comment]
@leseb That did the trick!

Thanks for your help today and this great tool!

**Comment by leseb** [comment]
Thanks for reporting the bug in the first place :).
Now both kraken and jewel are back in business :).
