### ISSUE TITLE
Add debug/verbose flags for commands

### ISSUE THREAD

**Issue by rimolive** [ceph/cn#60]
I'm trying to debug a connection refused issue with my Python code and I tested some bucket operations with `cn s3` command. However, if I had a way to add `--verbose` or `--debug` to check the API interactions would be better to troubleshoot the connection issue.

**Comment by leseb** [comment]
This is possible but you will only see the `debug` output of `s3cmd`, how does that sound?

**Comment by rimolive** [comment]
Any other way to check ceph logs or something? maybe a wrapper that could spit ceph logging messages so it's possible to inspect ceph behavior. to be honest, I'm ok if we conclude that a troubleshooting guide fits better in this issue.

**Comment by leseb** [comment]
What about `cn cluster logs $cluster`? You will see the rgw logs.

**Comment by leseb** [comment]
Fix in #79
