### ISSUE TITLE
Use native S3 calls

### ISSUE THREAD

**Issue by leseb** [ceph/cn#9]
Currently `cn` uses s3cmd as a wrapper this works, but a nice enhancement would be to do native S3 API calls instead.

**Comment by mattbenjamin** [comment]
This would be very nice.

Matt

**Comment by leseb** [comment]
https://github.com/aws/aws-sdk-go

**Comment by leseb** [comment]
Will likely never happen since we have the wrapper around `s3cmd` and soon the UI AND obviously the API endpoint, it should be enough already for people to play.
