### ISSUE TITLE
Configurable resources

### ISSUE THREAD

**Issue by rapatel0** [ceph/cn#94]
I'm trying to build a dev environment to reproduce an issue we are seeing in production. The issue is that ceph nano tops out at 512MB of RAM. An OOM error just hoses the container.

**Comment by leseb** [comment]
Are you saying the container dies because the memory goes above 512MB?

**Comment by ErwanAliasr1** [comment]
Can you describe how you went into this case ? How old was your container, what operation did you took, is it reproducible ? What version of ceph/ceph-container ?
thx.

**Comment by ErwanAliasr1** [comment]
I've been able to reproduce. I'll track this issue. That sound like a ceph leak.

**Comment by leseb** [comment]
Closed via #100
